<?php

return [
    'account_with_name_comparism' => [
        'label' => 'Account with Name Comparism',
        'method' => 'POST',
        'path' => '/verification/bank_account/comparism',
        'docs_url' => 'https://docs.prembly.com/docs/bank-accounts-comparism-copy',
        'countries' => ['NG'],
        'required' => true,
        'normalizer' => 'account_name_match',
        'service' => [
            'code' => 'ACCOUNT_WITH_NAME_COMPARISM',
            'name' => 'Account with Name Comparism',
            'type' => 'bank',
            'country' => 'NG',
            'default_price' => 100,
            'default_cost' => 70,
            'is_active' => true,
            'featured' => true,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'Bank account number'],
            ['name' => 'bank_code', 'type' => 'string', 'required' => true, 'description' => 'Bank code'],
            ['name' => 'customer', 'type' => 'string', 'required' => true, 'description' => "Customer name (docs label this key as 'customer' while the test data shows 'customer_name')."],
        ],
    ],
    'address_verification' => [
        'label' => 'Address Verification',
        'method' => 'POST',
        'path' => '/verification/address',
        'docs_url' => 'https://docs.prembly.com/docs/address-verification-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'ADDRESS_VERIFICATION',
            'name' => 'Address Verification',
            'type' => 'address',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => true,
        ],
        'request_body' => [
            ['name' => 'first_name', 'type' => 'string', 'required' => true, 'description' => 'First name of the customer'],
            ['name' => 'last_name', 'type' => 'string', 'required' => true, 'description' => 'Last name of the customer'],
            ['name' => 'phone', 'type' => 'string', 'required' => true, 'description' => 'Phone number of the customer'],
            ['name' => 'address', 'type' => 'string', 'required' => true, 'description' => 'Full address'],
            ['name' => 'landmark', 'type' => 'string', 'required' => false, 'description' => 'Landmark associated with the address'],
            ['name' => 'street', 'type' => 'string', 'required' => false, 'description' => 'Street'],
            ['name' => 'city', 'type' => 'string', 'required' => false, 'description' => 'City'],
            ['name' => 'state', 'type' => 'string', 'required' => true, 'description' => 'State'],
            ['name' => 'lga', 'type' => 'string', 'required' => true, 'description' => 'Local Government Area'],
            ['name' => 'verification_type', 'type' => 'string', 'required' => true, 'default' => 'person', 'description' => "Verification type (docs show 'person')."],
            ['name' => 'address_verification_due_date', 'type' => 'string', 'required' => false, 'description' => 'Due date for address verification in YYYY-MM-DD format'],
        ],
    ],
    'address_verification_status' => [
        'label' => 'Address Verification Status',
        'method' => 'POST',
        'path' => '/verification/address/status',
        'docs_url' => 'https://docs.prembly.com/docs/address-verification-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'ADDRESS_VERIFICATION_STATUS',
            'name' => 'Address Verification Status',
            'type' => 'address',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'job_id', 'type' => 'string', 'required' => true, 'description' => 'The _id returned by the address verification response'],
        ],
    ],
    'bank_account_basic' => [
        'label' => 'Bank Account (Basic)',
        'method' => 'POST',
        'path' => '/verification/bank_account/basic',
        'docs_url' => 'https://docs.prembly.com/docs/bank-accounts-basic-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'BANK_ACCOUNT_BASIC',
            'name' => 'Bank Account (Basic)',
            'type' => 'bank',
            'country' => 'NG',
            'default_price' => 90,
            'default_cost' => 60,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'Bank account number'],
            ['name' => 'bank_code', 'type' => 'string', 'required' => true, 'description' => 'Bank code'],
        ],
    ],
    'list_bank_code' => [
        'label' => 'List Bank Code',
        'method' => 'GET',
        'path' => '/identitypass/verification/bank_account/bank_code',
        'docs_url' => 'https://docs.prembly.com/reference/get_identitypass-verification-bank-account-bank-code',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'LIST_BANK_CODE',
            'name' => 'List Bank Code',
            'type' => 'utility',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'GET endpoint with no request body.',
    ],
    'basic_cac' => [
        'label' => 'Basic CAC',
        'method' => 'POST',
        'path' => '/verification/cac',
        'docs_url' => 'https://docs.prembly.com/docs/basic-cac-copy',
        'countries' => ['NG'],
        'required' => true,
        'normalizer' => 'cac',
        'service' => [
            'code' => 'BASIC_CAC',
            'name' => 'Basic CAC',
            'type' => 'kyb',
            'country' => 'NG',
            'default_price' => 350,
            'default_cost' => 240,
            'is_active' => true,
            'featured' => true,
        ],
        'request_body' => [
            ['name' => 'rc_number', 'type' => 'string', 'required' => true, 'description' => 'Company registration number'],
            ['name' => 'company_type', 'type' => 'string', 'required' => false, 'default' => 'RC', 'description' => 'BN or RC or IT'],
            ['name' => 'company_name', 'type' => 'string', 'required' => false, 'description' => 'Company name'],
        ],
    ],
    'advance_cac' => [
        'label' => 'Advance CAC',
        'method' => 'POST',
        'path' => '/verification/cac/advance',
        'docs_url' => 'https://docs.prembly.com/docs/advance-cac-copy',
        'countries' => ['NG'],
        'required' => true,
        'normalizer' => 'cac',
        'service' => [
            'code' => 'ADVANCE_CAC',
            'name' => 'Advance CAC',
            'type' => 'kyb',
            'country' => 'NG',
            'default_price' => 400,
            'default_cost' => 280,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'rc_number', 'type' => 'string', 'required' => true, 'description' => 'Company registration number'],
            ['name' => 'company_type', 'type' => 'string', 'required' => false, 'default' => 'RC', 'description' => 'BN or RC or IT'],
            ['name' => 'company_name', 'type' => 'string', 'required' => false, 'description' => 'Company name'],
        ],
    ],
    'business_address_verification' => [
        'label' => 'Business Address Verification',
        'method' => 'POST',
        'path' => '/identitypass/verification/address',
        'docs_url' => 'https://docs.prembly.com/reference/address-verification-copy-1',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'BUSINESS_ADDRESS_VERIFICATION',
            'name' => 'Business Address Verification',
            'type' => 'kyb',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'Reference page was not opened during extraction, so the service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'basic_phone_number' => [
        'label' => 'Basic Phone Number',
        'method' => 'POST',
        'path' => '/verification/phone_number',
        'docs_url' => 'https://docs.prembly.com/docs/basic-phone-number-copy',
        'countries' => ['NG'],
        'required' => true,
        'normalizer' => 'phone',
        'service' => [
            'code' => 'BASIC_PHONE_NUMBER',
            'name' => 'Basic Phone Number',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 120,
            'default_cost' => 80,
            'is_active' => true,
            'featured' => true,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'Phone number'],
        ],
    ],
    'advance_phone_number' => [
        'label' => 'Advance Phone Number',
        'method' => 'POST',
        'path' => '/verification/phone_number/advance',
        'docs_url' => 'https://docs.prembly.com/reference/advance-phone-number-1',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'ADVANCE_PHONE_NUMBER',
            'name' => 'Advance Phone Number',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The fetched docs pointed to a different global endpoint, so this stays off until the exact Nigerian request body is confirmed.',
    ],
    'bvn_basic' => [
        'label' => 'BVN Basic',
        'method' => 'POST',
        'path' => '/verification/bvn_validation',
        'docs_url' => 'https://docs.prembly.com/docs/bvn-basic-copy',
        'countries' => ['NG'],
        'required' => true,
        'normalizer' => 'bvn',
        'service' => [
            'code' => 'BVN_BASIC',
            'name' => 'BVN Basic',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 150,
            'default_cost' => 95,
            'is_active' => true,
            'featured' => true,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'Bank Verification Number'],
        ],
    ],
    'bvn_advance' => [
        'label' => 'BVN Advance',
        'method' => 'POST',
        'path' => '/verification/bvn',
        'docs_url' => 'https://docs.prembly.com/docs/bvn-advance-copy',
        'countries' => ['NG'],
        'required' => true,
        'normalizer' => 'bvn',
        'service' => [
            'code' => 'BVN_ADVANCE',
            'name' => 'BVN Advance',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 180,
            'default_cost' => 120,
            'is_active' => true,
            'featured' => true,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'Bank Verification Number'],
        ],
    ],
    'bvn_face_validation' => [
        'label' => 'BVN + Face Validation',
        'method' => 'POST',
        'path' => '/verification/bvn_w_face',
        'docs_url' => 'https://docs.prembly.com/docs/bvn-face-validation-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'BVN_FACE_VALIDATION',
            'name' => 'BVN + Face Validation',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 250,
            'default_cost' => 180,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'Bank Verification Number'],
            ['name' => 'image', 'type' => 'string', 'required' => true, 'description' => 'Image URL or base64 encoded PNG/JPEG'],
        ],
    ],
    'get_bvn_with_phone_number' => [
        'label' => 'Get BVN with Phone Number',
        'method' => 'POST',
        'path' => '/verification/bvn_with_phone_advance',
        'docs_url' => 'https://docs.prembly.com/reference/get-bvn-with-phone-number-1',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'GET_BVN_WITH_PHONE_NUMBER',
            'name' => 'Get BVN with Phone Number',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'financial_accounts_advance' => [
        'label' => 'Financial Accounts Advance',
        'method' => 'POST',
        'path' => '/verification/list/financial_accounts/advance',
        'docs_url' => 'https://docs.prembly.com/docs/financial-accounts-advance-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'FINANCIAL_ACCOUNTS_ADVANCE',
            'name' => 'Financial Accounts Advance',
            'type' => 'bank',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'BVN'],
            ['name' => 'verify_with', 'type' => 'string', 'required' => true, 'description' => 'Contact detail to receive the OTP'],
            ['name' => 'otp', 'type' => 'string', 'required' => true, 'description' => 'OTP sent to the preferred contact'],
        ],
    ],
    'nin_basic' => [
        'label' => 'NIN Basic (vNIN-basic)',
        'method' => 'POST',
        'path' => '/verification/vnin-basic',
        'docs_url' => 'https://docs.prembly.com/docs/national-id-basic-1',
        'countries' => ['NG'],
        'required' => true,
        'normalizer' => 'nin',
        'service' => [
            'code' => 'NIN_BASIC',
            'name' => 'NIN Basic (vNIN-basic)',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 200,
            'default_cost' => 130,
            'is_active' => true,
            'featured' => true,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => "User's NIN"],
        ],
    ],
    'nin_advance' => [
        'label' => 'NIN (vNIN/NIN) Advance',
        'method' => 'POST',
        'path' => '/verification/vnin',
        'docs_url' => 'https://docs.prembly.com/docs/nin-and-virtual-nin-copy',
        'countries' => ['NG'],
        'required' => true,
        'normalizer' => 'nin',
        'one_of' => [
            ['number', 'number_nin'],
        ],
        'service' => [
            'code' => 'NIN_ADVANCE',
            'name' => 'NIN (vNIN/NIN) Advance',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 220,
            'default_cost' => 150,
            'is_active' => true,
            'featured' => true,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => false, 'description' => 'Virtual NIN'],
            ['name' => 'number_nin', 'type' => 'string', 'required' => false, 'description' => 'NIN'],
        ],
        'notes' => 'Provide exactly one of number or number_nin.',
    ],
    'nin_with_face' => [
        'label' => 'NIN With Face',
        'method' => 'POST',
        'path' => '/verification/nin_w_face',
        'docs_url' => 'https://docs.prembly.com/docs/nin-with-face-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'NIN_WITH_FACE',
            'name' => 'NIN With Face',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 260,
            'default_cost' => 190,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'NIN number'],
            ['name' => 'image', 'type' => 'string', 'required' => true, 'description' => 'Image URL or base64 encoded PNG/JPEG'],
        ],
    ],
    'nin_level_2' => [
        'label' => 'NIN (NinAuth Level 2)',
        'method' => 'POST',
        'path' => '/verification/nin-level-2',
        'docs_url' => 'https://docs.prembly.com/reference/nin-basic',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'NIN_LEVEL_2',
            'name' => 'NIN (NinAuth Level 2)',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'advance_drivers_license' => [
        'label' => 'Advance Drivers License',
        'method' => 'POST',
        'path' => '/verification/drivers_license/advance',
        'docs_url' => 'https://docs.prembly.com/docs/advance-drivers-license-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'ADVANCE_DRIVERS_LICENSE',
            'name' => 'Advance Drivers License',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'License number'],
            ['name' => 'dob', 'type' => 'string', 'required' => true, 'description' => 'Date of birth in YYYY-MM-DD format'],
            ['name' => 'first_name', 'type' => 'string', 'required' => true, 'description' => 'First name'],
            ['name' => 'last_name', 'type' => 'string', 'required' => true, 'description' => 'Last name'],
        ],
    ],
    'drivers_license_face_validation' => [
        'label' => 'Drivers License + Face Validation',
        'method' => 'POST',
        'path' => '/verification/drivers_license/face',
        'docs_url' => 'https://docs.prembly.com/docs/drivers-license-face-validation-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'DRIVERS_LICENSE_FACE_VALIDATION',
            'name' => 'Drivers License + Face Validation',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'image', 'type' => 'string', 'required' => true, 'description' => 'Image in base64, PNG, or JPG'],
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'FRSC number'],
            ['name' => 'dob', 'type' => 'string', 'required' => true, 'description' => 'Date of birth in YYYY-MM-DD format'],
        ],
    ],
    'drivers_license_image' => [
        'label' => 'Drivers License (Image)',
        'method' => 'POST',
        'path' => '/verification/drivers_license/image',
        'docs_url' => 'https://docs.prembly.com/reference/drivers-license-image',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'DRIVERS_LICENSE_IMAGE',
            'name' => 'Drivers License (Image)',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not found quickly during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'international_passport' => [
        'label' => 'International Passport',
        'method' => 'POST',
        'path' => '/verification/national_passport',
        'docs_url' => 'https://docs.prembly.com/reference/international-passport',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'INTERNATIONAL_PASSPORT',
            'name' => 'International Passport',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'international_passport_face_validation' => [
        'label' => 'International Passport + Face Validation',
        'method' => 'POST',
        'path' => '/verification/national_passport_with_face',
        'docs_url' => 'https://docs.prembly.com/reference/international-passport-face-validation',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'INTERNATIONAL_PASSPORT_FACE_VALIDATION',
            'name' => 'International Passport + Face Validation',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'international_passport_image' => [
        'label' => 'International Passport (Image)',
        'method' => 'POST',
        'path' => '/identitypass/verification/national_passport_image',
        'docs_url' => 'https://docs.prembly.com/reference/post_identitypass-verification-national-passport-image',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'INTERNATIONAL_PASSPORT_IMAGE',
            'name' => 'International Passport (Image)',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'passport_version_2' => [
        'label' => 'Passport Version 2',
        'method' => 'POST',
        'path' => '/verification/national_passport_v2',
        'docs_url' => 'https://docs.prembly.com/docs/passport-version-2-1',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'PASSPORT_VERSION_2',
            'name' => 'Passport Version 2',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'last_name', 'type' => 'string', 'required' => true, 'description' => "User's surname"],
            ['name' => 'dob', 'type' => 'string', 'required' => true, 'description' => 'Date of birth in YYYY-MM-DD format'],
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'Passport number'],
        ],
    ],
    'plate_number_verification' => [
        'label' => 'Plate Number Verification',
        'method' => 'POST',
        'path' => '/verification/vehicle',
        'docs_url' => 'https://docs.prembly.com/docs/plate-number-verification-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'PLATE_NUMBER_VERIFICATION',
            'name' => 'Plate Number Verification',
            'type' => 'vehicle',
            'country' => 'NG',
            'default_price' => 150,
            'default_cost' => 100,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'vehicle_number', 'type' => 'string', 'required' => true, 'description' => 'Vehicle plate number'],
        ],
    ],
    'stamp_duty' => [
        'label' => 'Stamp Duty',
        'method' => 'POST',
        'path' => '/verification/stamp_duty',
        'docs_url' => 'https://docs.prembly.com/docs/stamp-duty-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'STAMP_DUTY',
            'name' => 'Stamp Duty',
            'type' => 'compliance',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'Stamp duty number'],
            ['name' => 'customer_name', 'type' => 'string', 'required' => true, 'description' => 'Customer name'],
        ],
    ],
    'voters_card' => [
        'label' => 'Voters Card',
        'method' => 'POST',
        'path' => '/verification/voters_card',
        'docs_url' => 'https://docs.prembly.com/docs/voters-identification-number-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'VOTERS_CARD',
            'name' => 'Voters Card',
            'type' => 'kyc',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => "Voter's card number"],
        ],
    ],
    'waec_verification' => [
        'label' => 'WAEC Verification',
        'method' => 'POST',
        'path' => '/identitypass/verification/waec',
        'docs_url' => 'https://docs.prembly.com/docs/waec-verification-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'WAEC_VERIFICATION',
            'name' => 'WAEC Verification',
            'type' => 'education',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'exam_number', 'type' => 'string', 'required' => true, 'description' => 'Examination number'],
            ['name' => 'exam_year', 'type' => 'string', 'required' => true, 'description' => 'Year of examination'],
            ['name' => 'exam_type', 'type' => 'string', 'required' => true, 'description' => 'Exam type such as waec'],
        ],
    ],
    'tin' => [
        'label' => 'Tax Identification Number (TIN)',
        'method' => 'POST',
        'path' => '/verification/tin',
        'docs_url' => 'https://docs.prembly.com/docs/tax-identification-number-tin-copy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'TIN',
            'name' => 'Tax Identification Number (TIN)',
            'type' => 'compliance',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => true,
        ],
        'request_body' => [
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => 'TIN or RC number or phone number'],
            ['name' => 'channel', 'type' => 'string', 'required' => false, 'default' => 'TIN', 'description' => 'TIN, CAC, or PHONE'],
        ],
    ],
    'insurance_policy' => [
        'label' => 'Insurance Policy',
        'method' => 'POST',
        'path' => '/verification/insurance_policy',
        'docs_url' => 'https://docs.prembly.com/docs/insurance-policy',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'INSURANCE_POLICY',
            'name' => 'Insurance Policy',
            'type' => 'compliance',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'channel', 'type' => 'string', 'required' => true, 'description' => 'Channel to check with, such as Policy'],
            ['name' => 'number', 'type' => 'string', 'required' => true, 'description' => "Customer's insurance or policy number"],
        ],
    ],
    'credit_bureau_consumer_advance' => [
        'label' => 'Credit Bureau Consumer (Individual) Advance',
        'method' => 'POST',
        'path' => '/verification/credit_bureau/consumer/advance',
        'docs_url' => 'https://docs.prembly.com/docs/credit-bureau-consumerindividual-advance-copy-1',
        'countries' => ['NG'],
        'required' => true,
        'service' => [
            'code' => 'CREDIT_BUREAU_CONSUMER_ADVANCE',
            'name' => 'Credit Bureau Consumer (Individual) Advance',
            'type' => 'compliance',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => true,
            'featured' => false,
        ],
        'request_body' => [
            ['name' => 'mode', 'type' => 'string', 'required' => true, 'description' => 'Either ID or BIO'],
            ['name' => 'number', 'type' => 'string', 'required' => false, 'description' => 'If mode is ID, this should be the BVN'],
            ['name' => 'dob', 'type' => 'string', 'required' => false, 'description' => 'If mode is BIO, this should be the date of birth'],
            ['name' => 'customer_name', 'type' => 'string', 'required' => true, 'description' => 'Customer name'],
            ['name' => 'customer_reference', 'type' => 'string', 'required' => true, 'description' => 'Unique customer reference'],
            ['name' => 'crb_provider', 'type' => 'string', 'required' => false, 'description' => 'crc or first-central'],
        ],
        'notes' => 'If mode is ID, send number. If mode is BIO, send dob.',
    ],
    'credit_bureau_consumer_basic' => [
        'label' => 'Credit Bureau Consumer (Individual) Basic',
        'method' => 'POST',
        'path' => '/verification/credit_bureau/consumer/basic',
        'docs_url' => 'https://docs.prembly.com/reference/credit-bureau-consumerindividual-basic',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'CREDIT_BUREAU_CONSUMER_BASIC',
            'name' => 'Credit Bureau Consumer (Individual) Basic',
            'type' => 'compliance',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'credit_bureau_commercial_basic' => [
        'label' => 'Credit Bureau Commercial (Business) Basic',
        'method' => 'POST',
        'path' => '/verification/credit_bureau/commercial/basic',
        'docs_url' => 'https://docs.prembly.com/reference/credit-bureau-commercialbusiness-basic',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'CREDIT_BUREAU_COMMERCIAL_BASIC',
            'name' => 'Credit Bureau Commercial (Business) Basic',
            'type' => 'kyb',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'credit_bureau_commercial_advance' => [
        'label' => 'Credit Bureau Commercial (Business) Advance',
        'method' => 'POST',
        'path' => '/verification/credit_bureau/commercial/advance',
        'docs_url' => 'https://docs.prembly.com/reference/credit-bureau-commercialbusiness-advance',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'CREDIT_BUREAU_COMMERCIAL_ADVANCE',
            'name' => 'Credit Bureau Commercial (Business) Advance',
            'type' => 'kyb',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'get_tin_with_phone_number' => [
        'label' => 'Get TIN with Phone Number',
        'method' => 'POST',
        'path' => '/verification/get-tin-with-phone',
        'docs_url' => 'https://docs.prembly.com/reference/get-tin-with-phone-number',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'GET_TIN_WITH_PHONE_NUMBER',
            'name' => 'Get TIN with Phone Number',
            'type' => 'compliance',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'scuml' => [
        'label' => 'SCUML',
        'method' => 'POST',
        'path' => '/verification/scuml',
        'docs_url' => 'https://docs.prembly.com/reference/scuml',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'SCUML',
            'name' => 'SCUML',
            'type' => 'compliance',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'tcc_checker' => [
        'label' => 'TCC Checker',
        'method' => 'POST',
        'path' => '/verification/tcc',
        'docs_url' => 'https://docs.prembly.com/reference/tcc',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'TCC_CHECKER',
            'name' => 'TCC Checker',
            'type' => 'compliance',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'metre_number' => [
        'label' => 'Metre Number',
        'method' => 'POST',
        'path' => '/verification/ng/meter/verify',
        'docs_url' => 'https://docs.prembly.com/reference/metre-number',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'METRE_NUMBER',
            'name' => 'Metre Number',
            'type' => 'utility',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
    'nysc' => [
        'label' => 'NYSC',
        'method' => 'POST',
        'path' => '/verification/nysc',
        'docs_url' => 'https://docs.prembly.com/reference/nysc-1',
        'countries' => ['NG'],
        'required' => false,
        'json_payload_fallback' => true,
        'service' => [
            'code' => 'NYSC',
            'name' => 'NYSC',
            'type' => 'education',
            'country' => 'NG',
            'default_price' => 0,
            'default_cost' => 0,
            'is_active' => false,
            'featured' => false,
        ],
        'request_body' => [],
        'notes' => 'The reference page was not opened during extraction, so this service uses JSON payload fallback until the exact body is confirmed.',
    ],
];
